# Czech letters

name: czech-letters
parent: default

matches:
  - trigger: "a'"
    replace: "á"
  - trigger: "A'"
    replace: "Á"
  - trigger: "c^"
    replace: "č"
  - trigger: "C^"
    replace: "Č"
  - trigger: "d^"
    replace: "ď"
  - trigger: "D^"
    replace: "Ď"
  - trigger: "e'"
    replace: "é"
  - trigger: "E'"
    replace: "É"
  - trigger: "e^"
    replace: "ě"
  - trigger: "E^"
    replace: "Ě"
  - trigger: "i'"
    replace: "í"
  - trigger: "I'"
    replace: "Í"
  - trigger: "n^"
    replace: "ň"
  - trigger: "N^"
    replace: "Ň"
  - trigger: "o'"
    replace: "ó"
  - trigger: "O'"
    replace: "Ó"
  - trigger: "r^"
    replace: "ř"
  - trigger: "R^"
    replace: "Ř"
  - trigger: "s^"
    replace: "š"
  - trigger: "S^"
    replace: "Š"
  - trigger: "t^"
    replace: "ť"
  - trigger: "T^"
    replace: "Ť"
  - trigger: "u'"
    replace: "ú"
  - trigger: "u^"
    replace: "ů"
  - trigger: "U^"
    replace: "Ů"
  - trigger: "y'"
    replace: "ý"
  - trigger: "Y'"
    replace: "Ý"
  - trigger: "z^"
    replace: "ž"
  - trigger: "Z^"
    replace: "Ž"

